name: CI

on:
  # Executa sempre que tiver algum commit na branche master
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # pega a versao mais atualizada do codigo
      - uses: actions/checkout@v2
      
      #configurações do ambiente
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.x
      
      # Instalar as dependencias (yarn/npm)
      - name: Install dependencies
        run: yarn
        
        # Executar o build do projeto
      - name: Run build
        run: yarn build
        
      - name: copy files to Digital Ocean
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{secrets.SSH_KEY}}
          source: "*, !node_modules"
          target: "test"
        
       
      # executar o yarn
      # executar as migrations
      # Restart servidor Node.js
      

   
